// Mocks generated by Mockito 5.1.0 from annotations
// in my_flutter_test/test/screens/counter/counter_viewmodel_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_flutter_test/use_cases/counter_decrement.dart' as _i3;
import 'package:my_flutter_test/use_cases/counter_increment.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [CounterIncrement].
///
/// See the documentation for Mockito's code generation for more information.
class MockCounterIncrement extends _i1.Mock implements _i2.CounterIncrement {
  MockCounterIncrement() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int call() =>
      (super.noSuchMethod(Invocation.method(#call, []), returnValue: 0) as int);
}

/// A class which mocks [CounterDecrement].
///
/// See the documentation for Mockito's code generation for more information.
class MockCounterDecrement extends _i1.Mock implements _i3.CounterDecrement {
  MockCounterDecrement() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int call() =>
      (super.noSuchMethod(Invocation.method(#call, []), returnValue: 0) as int);
}
